services:
  frontend:
    build: ./frontend
    ports:
      - "5111:5111"
    env_file: ./frontend/.env.local
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5160:5160"
    env_file: ./backend/.env

  discord-bot:
    build: ./discord-bot
    env_file: ./discord-bot/.env
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
