FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o bot ./cmd/bot

FROM alpine:latest
RUN apk --no-cache add tzdata ca-certificates
WORKDIR /app
COPY --from=builder /app/bot .
CMD ["./bot"]
